create TABLE TB_USER (
    ID bigserial primary key not null,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(15) NOT NULL,
    USER_NAME VARCHAR(30)
);

create TABLE TB_TASK (
    ID bigserial primary key not null,
    USER_ID int8 NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),-- pode ser inserida sem nada inicialmente
    STATUS NUMERIC(1) NOT NULL,-- 1(PENDING),2(COMPLETED)
    DATE_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATE_UPDATE TIMESTAMP,
    CONSTRAINT TB_TASK_USER_FK FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID)
);